version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: ai-doorbell-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=ai-doorbell
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d
      - mongodb_data:/data/db
    networks:
      - ai-doorbell-network

  # MongoDB Express web-based interface (optional)
  mongo-express:
    image: mongo-express:latest
    container_name: ai-doorbell-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      - mongodb
    networks:
      - ai-doorbell-network

volumes:
  mongodb_data:

networks:
  ai-doorbell-network:
    driver: bridge